// See https://aka.ms/new-console-template for more information
using static System.Runtime.InteropServices.JavaScript.JSType;

Console.WriteLine("Hello, World!");
int number = 0;
char simvol = 'ы';
string stroka = "ыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыыы";
double pi = 3.14;
bool bull = false;
Console.WriteLine($"Переменная number, значение {number}");
Console.WriteLine($"Переменная simvol, значение {simvol}");
Console.WriteLine($"Переменная stroka, значение {stroka}");
Console.WriteLine($"Переменная pi, значение {pi}");
Console.WriteLine($"Переменная bull, значение {bull}");
Console.WriteLine("");
Console.WriteLine($"number: {number}, Type: {number.GetType()}");
Console.WriteLine($"number: {simvol}, Type: {simvol.GetType()}");
Console.WriteLine($"number: {stroka}, Type: {stroka.GetType()}");
Console.WriteLine($"number: {pi}, Type: {pi.GetType()}");
Console.WriteLine($"number: {bull}, Type: {bull.GetType()}");
Console.WriteLine("");
number = 224;
simvol = 'a';
stroka = "aaaaaaaaaaaaaaaaaaaaaaaaaa";
pi = 2.71;
bull = true;
Console.WriteLine($"Переменная number, значение {number}");
Console.WriteLine($"Переменная simvol, значение {simvol}");
Console.WriteLine($"Переменная stroka, значение {stroka}");
Console.WriteLine($"Переменная pi, значение {pi}");
Console.WriteLine($"Переменная bull, значение {bull}");
Console.WriteLine("");
const int n = 424;
const char yo = 'ё';
const string strichka = "Life";
const double double_pi = 6.28;
const bool one = true;
Console.WriteLine($"Переменная n, значение {n}");
Console.WriteLine($"Переменная yo, значение {yo}");
Console.WriteLine($"Переменная strichka, значение {strichka}");
Console.WriteLine($"Переменная double_pi, значение {double_pi}");
Console.WriteLine($"Переменная one, значение {one}");
//one = false;
Console.WriteLine("");
bool alive = true;
byte bit = 102;
sbyte bit1 = -101;
short n1 = 1;
ushort n2 = 102;
int a = 10;
uint b = 10;
long c = -10;
ulong d = 10;
float e = 4.5f;
double f = 2.87;
decimal g = 10.623146758m;
char chart = 'A';
string struchka = "4512354";
Console.WriteLine($"Переменная alive, значение {alive}");
Console.WriteLine($"Переменная bit, значение {bit}");
Console.WriteLine($"Переменная bit1, значение {bit1}");
Console.WriteLine($"Переменная n1, значение {n1}");
Console.WriteLine($"Переменная n2, значение {n2}");
Console.WriteLine($"Переменная a, значение {a}");
Console.WriteLine($"Переменная b, значение {b}");
Console.WriteLine($"Переменная d, значение {c}");
Console.WriteLine($"Переменная d, значение {d}");
Console.WriteLine($"Переменная e, значение {e}");
Console.WriteLine($"Переменная f, значение {f}");
Console.WriteLine($"Переменная g, значение {g}");
Console.WriteLine($"Переменная chart, значение {chart}");
Console.WriteLine($"Переменная struchka, значение {struchka}");
Console.WriteLine("");
float suffix_a = 3.14F;
decimal suffix_c = 1005.8M;
uint suffix_b = 10U;
long suffix_d = 20L;
ulong suffix_e = 30UL;
Console.WriteLine($"Переменная suffix_a, значение {suffix_a}");
Console.WriteLine($"Переменная suffix_c, значение {suffix_c}");
Console.WriteLine($"Переменная suffix_b, значение {suffix_b}");
Console.WriteLine($"Переменная suffix_d, значение {suffix_d}");
Console.WriteLine($"Переменная suffix_e, значение {suffix_e}");
Console.WriteLine("");
System.Int32 system_a = 4;
System.Char system_b = 'k';
System.String system_c = "dbndl";
System.Double system_d = 5;
System.Boolean system_e = true;
Console.WriteLine($"Переменная system_a, значение {system_a}");
Console.WriteLine($"Переменная system_b, значение {system_b}");
Console.WriteLine($"Переменная system_c, значение {system_c}");
Console.WriteLine($"Переменная system_d, значение {system_d}");
Console.WriteLine($"Переменная system_e, значение {system_e}");
Console.WriteLine("");
number = 5;
simvol = 'я';
stroka = "еееееееееееееееееее";
pi = 3.13;
bull = true;
Console.WriteLine($"Переменная number, значение {number}");
Console.WriteLine($"Переменная simvol, значение {simvol}");
Console.WriteLine($"Переменная stroka, значение {stroka}");
Console.WriteLine($"Переменная pi, значение {pi}");
Console.WriteLine($"Переменная bull, значение {bull}");
Console.WriteLine("");
int i = 6;
float j = 9.0f;
double k = 2.03;
j = i;
k = i;
k = j;
Console.WriteLine($"Переменная i, значение {i}");
Console.WriteLine($"Переменная j, значение {j}");
Console.WriteLine($"Переменная k, значение {k}");
Console.WriteLine("");
int l = 4;
char m = 't';
double m2 = 1.32;
m = (char)l;
m2 = (float)l;
l = (char)m;
Console.WriteLine($"Переменная l, значение {l}");
Console.WriteLine($"Переменная m, значение {m}");
Console.WriteLine($"Переменная m2, значение {m2}");
Console.WriteLine("");
float o = 1.1f;
int p = 2;
string q = "iii";
o = Convert.ToInt32(true);
p = Convert.ToByte(true);
q = Convert.ToString(true);
Console.WriteLine($"Переменная o, значение {o}");
Console.WriteLine($"Переменная p, значение {p}");
Console.WriteLine($"Переменная q, значение {q}");
Console.WriteLine("");
